Check the docker daemon MTU setting
rancher/plugin-manager pull request #85
Opened 2017-08-28 13:55 UTC by niusmallnan

https://github.com/rancher/rancher/issues/7583

2017-08-28 13:56 UTC, niusmallnan commented
if the Docker daemon is configured with different MTU than the configured when launching the catalog. 
```
time="2017-08-28T13:50:29Z" level=error msg="Failed to apply cni conf: Get different MTU, cni:1600, docker:1450"
```

2017-08-29 06:22 UTC, leodotcloud requested changes

2017-08-29 06:22 UTC, leodotcloud commented on cniconf/watcher.go
> +			continue
Don't `continue`, just a log is good.
```
logrus.Errorf("cniconf: Docker Bridge MTU %v is different from CNI config MTU: %v", dockerBridgeMTU, cniConfigMTU);
```

2017-08-29 06:22 UTC, leodotcloud commented on cniconf/watcher.go
> +	for _, n := range networks {
Can you please split the functionality of getting the MTU from docker as a separate function?
`func GetDockerNetworkBridgeMTU(string bridgeName)`

2017-09-09 07:05 UTC, leodotcloud commented
@niusmallnan does this work if we change the bridge in IPSec or VXLAN catalog from docker0 to rancher0?

2017-09-09 07:08 UTC, leodotcloud commented on cniconf/watcher.go
> +		logrus.Errorf("checkMTU: Get error from docker api: %s", err)
Minor typo: Should be `Got error from docker api:`

2017-09-12 06:58 UTC, niusmallnan commented
@leodotcloud 
In that case, rancher0 bridge will be created by `rancher-cni-bridge` and get the correct MTU.
In addition, these code will determine whether the bridge is Docker Bridge.

2017-09-15 07:43 UTC, leodotcloud approved these changes

2017-09-15 07:43 UTC, leodotcloud commented
LGTM

2017-09-15 07:43 UTC, merged